.evg.yml

I don't think we need to do this anymore since we publish to NPM

chore(build) remove tarball upload from dist

---

.evg.yml

@edaniels this fixes the tests (was broken by the update to package structure).
This also addresses a similar problem as the one in your other PR for the server repo about the S3 keys. I deleted the branch-based bundle upload since I don't think anyone's relying on it, and they should be using `stable` anyway, so it seems safe to kill off.

fix(dist): use updated go run command and don't clobber s3 keys

---

package.json
src/auth/providers.js
src/client.js
test/auth.test.js
test/test.js

* Remove `login( ... )` method from anon & userpass providers (replace with authenticate methods)
* Move "if auth exists, re-use" logic to Stitch client's authenticate method (rather than living in auth provider's login method)
* Returns `json.userId` from Stitch client's authenticate method

STITCH-539 - Auth methods return only authed userId in body

---

test/admin/authProviders.test.js
test/admin/pipelines.test.js

@haleyowen 
Since we made the server-side change to include disabled auth providers, I think this test needed an update. I updated the change for enable/disable to what I think it should be; it seems to fix the "disable auth provider" test, but not the "enable" one - I'm not sure why. Any ideas?

Fix auth providers crud sdk test

---

src/client.js
test/admin/dev.test.js
test/admin/pipelines.test.js

* Implement `dev.executePipeline` method
* Update `v2._post` to accept query params in order to support `user_id` needed for dev pipeline execution
* Add simple test to ensure execution works

STITCH-764: Debug Console Pipeline Execution

---

src/admin.js
test/admin/service.test.js

These are the necessary JS SDK changes for STITCH-557 and STITCH-558. Tests won't pass on this until the STITCH-557 and STITCH-558 Stitch server changes are merged in.

STITCH-557 STITCH-558 add support for running service commands in the v2 admin api

---

src/admin.js
test/admin/api_keys.test.js
test/admin/app.test.js
test/admin/authProviders.test.js
test/admin/dev.test.js
test/admin/functions.test.js
test/admin/logs.test.js
test/admin/pipelines.test.js
test/admin/push.test.js
test/admin/service.test.js
test/admin/users.test.js
test/admin/values.test.js
test/services/mongodb.test.js

Recap for [STITCH-880](https://jira.mongodb.org/browse/STITCH-880):
* Moved `v3` endpoints to top level admin client `app( groupId )` function
* Removed `v1` endpoints entirely
* Maintains `v2` endpoints (with `v3` functionality omitted ... functions & dev execute function)
* The only test coverage for `v2` endpoints now are `pipelines.test.js` & one test in `dev.test.js` for executing pipelines.  **Should this change to have existing `v3` test files duplicated and ran against `v2` as well?**

STITCH-880 - Add admin v3.0 and remove admin v1.0/v2.0

---

.babelrc
package.json
test/errors.test.js

* Add `babel-plugin-transform-builtin-extend`
* Subclassing builtin types needs special treatment by babel
* Without this plugin, in a node environment, a subclass of Error does not actually behave like a true subclass, which manifests itself via a missing stacktrace when a StitchError is thrown
We've been seeing a handful of flaky tests in evergreen caused by uncaught promises. Because of the missing stacktraces, these errors are super hard to track down. This should help with that.

Fix StitchError stack traces in node

---

src/services/mongodb/collection.js
test/client/mongodb_service.test.js

cc @makesitgo so we have to back out the `.then`/`.catch` trick because it doesn't play so nicely with some promise APIs. An explicit `.execute()` method seems to be the best way to do this without it being too confusing.
will need to update the getting started example to include this change, i'll get to that next.

use .execute() to force execution of find queries

---

src/client.js
test/test.js

also some minor refactoring to constify the api types and added a test.
I think ultimately we should work on converting the rest of the test suites in the repo to just use a real server, it'll be less brittle. (see https://jira.mongodb.org/browse/STITCH-922)

fix session + profile root urls

---

src/services/http/http_service.js
test/client/http_service.test.js
test/fixtures/simple_http_server.js

**Test Output:**
```cmd
PASS  test/client/http_service.test.js
Executing http service functions
That have no matching service rules
✓ should fail due to no matching rule found (137ms)
That have proper service rules created
And an unavailable mock server
✓ should fail due to a function execution error (120ms)
And an available mock server
Submitting an invalid request
✓ should fail when an invalid url value is supplied (96ms)
✓ should fail when an invalid url datatype is supplied (80ms)
✓ should fail when both url and scheme+host are supplied (82ms)
Submitting a GET request
✓ with a string argument should send a successful request (114ms)
✓ with an object argument should send a successful request (87ms)
Submitting a POST request
✓ with a string argument should send a successful request and …
```

STITCH-931 - HTTP Service Integration Tests

---

src/client.js

With the React Native improvements, the return type for authedId() is now a promise, which should be properly documented

fix documented return type for authedId() in StitchClient

---

contrib/README.md

WIP
I want more instructions that get us to something like https://github.com/facebook/react/releases/tag/v16.2.0. Can start out unautomated but we can get automated tags in the meantime. Going to apply something like this to other SDKs.

Update contrib instructions for more useful changelog

---

docs_theme/assets/site.js
docs_theme/assets/style.css

Two small changes to the UI for the docs:
* Hash links to specific instance/static members (e.g. https://s3.amazonaws.com/stitch-sdks/js/docs/master/index.html#collectioninsertmany) of a class will automatically open the description of that member.
* In the list of instance/static members for each class, the clickable area to open the description now has a pointer cursor and a slight gray color when hovering.

STITCH-1180 Improve instance member links in generated documentation

---

src/auth/index.js

@jsflax this code causes some nasty issues on sites using fragments. They would essentially fail every single time a page is hit with a fragment since `redirectProvider` is undefined. It was incorrect to fail if `!redirectProvider `. The proper condition is redirect state found and `!redirectProvider`.
This code also fixes the returning early which worked in synchronous code but not here since we move onto the next promise that has undefined arguments. Now we reject to the last catch and continue on happily provided no real error was thrown/rejected.

STITCH-1217 - Handle irrelevant hash fragment correctly

---

.evg.yml

Preemptively doing this so the SDK repo doesn't break when https://github.com/10gen/stitch/pull/504 is merged in.

build transpiler and place onto PATH

---

.evg.yml
package-lock.json
package.json
test/admin/admin_users.test.js
test/admin/debug.test.js
test/admin/event_subscriptions.test.js
test/admin/hosting.test.js
test/admin/logs.test.js
test/admin/service.test.js
test/storage.test.js
test/test.js
test/testutil.js

Things still failing on Evergreen as of [this build](https://evergreen.mongodb.com/task/stitch_js_sdk_3.0_linux_64_run_tests_patch_d309cecb4a5ad12b9aaa714903b5a8ea9826edc5_5c05796f2fbabe111110e046_18_12_03_18_43_59):
- `test/test.js`
- `test/auth.test.js`
- `test/storage.test.js`
- ~`test/client/oauth.test.js`~

[STITCH-2183] Make support/3.x branch green again

---

packages/browser/services/http/__tests__/HttpServiceClientIntTests.ts
packages/core/services/http/__tests__/internal/CoreHttpServiceClientUnitTests.ts
packages/core/services/http/src/internal/ResultDecoders.ts
packages/react-native/services/http/__tests__/HttpServiceClientIntTests.ts
packages/server/services/http/__tests__/HttpServiceClientIntTests.ts

should be pretty straightforward, fixed a bug where headers decoder was being preallocated with undefined entries that were never filled

STITCH-2325 fix bug where decoded HTTP response headers contained undefined entry

---

contrib/stage_docs.sh
packages/browser/core/src/core/Stitch.ts
packages/browser/core/src/core/StitchAppClient.ts
packages/browser/core/src/core/auth/StitchAuth.ts
packages/browser/core/src/core/auth/StitchUser.ts
packages/browser/core/src/core/auth/providers/StitchRedirectCredential.ts
packages/browser/services/mongodb-remote/src/RemoteMongoClient.ts
packages/core/sdk/src/auth/StitchCredential.ts
packages/core/sdk/src/auth/providers/anonymous/AnonymousCredential.ts
packages/core/sdk/src/auth/providers/facebook/FacebookCredential.ts
packages/core/sdk/src/auth/providers/google/GoogleCredential.ts

- Adds links to pages related to authentication
- Clarifies purpose of some classes from a user perspective
- Hides non-redirect GoogleCredential and FacebookCredential,
as their auth providers are also hidden
Staged docs (start at StitchAppClient and navigate the auth flow):
https://docs-mongodbcom-staging.corp.mongodb.com/stitch/bush/docsp-auth/sdk/js/index.html

DOCSP-3942 Improve Authentication flow in SDK docs

---

package-lock.json
packages/browser/core/src/index.ts
packages/browser/coretest/__tests__/auth/providers/userapikey/UserApiKeyAuthProviderClientIntTests.ts
packages/browser/sdk/README.md
packages/browser/services/aws-s3/__tests__/AwsS3ServiceClientIntTests.ts
packages/browser/services/aws/__tests__/AwsServiceClientIntTests.ts
packages/browser/services/mongodb-remote/__tests__/RemoteMongoClientIntTests.ts
packages/core/sdk/src/index.ts
packages/core/testutils/src/BaseStitchIntTestHarness.ts
packages/react-native/core/package-lock.json
packages/react-native/core/src/index.ts
packages/react-native/coretest/__tests__/auth/providers/userapikey/UserApiKeyAuthProviderClientIntTests.ts
packages/react-native/sdk/README.md
packages/react-native/services/aws-s3/__tests__/AwsS3ServiceClientIntTests.ts
packages/react-native/services/aws/__tests__/AwsServiceClientIntTests.ts
packages/server/core/src/index.ts
packages/server/coretest/__tests__/auth/providers/userapikey/UserApiKeyAuthProviderClientIntTests.ts
packages/server/sdk/README.md
packages/server/services/aws-s3/__tests__/AwsS3ServiceClientIntTests.ts
packages/server/services/aws/__tests__/AwsServiceClientIntTests.ts
packages/server/services/mongodb-remote/__tests__/RemoteMongoClientIntTests.ts

Without the `package-lock.json` changes this PR is tiny.
Changes:
* imports `BSON from "bson"` and exports it at the `mongodb-stitch-core-sdk` level
* exports this `BSON` at the `mongodb-stitch-browser-core`, `mongodb-stitch-react-native-core`, and `mongodb-stitch-server-core` levels.
* all of the `*-sdk` modules get this `BSON` automatically because those modules `import * from` their respective core module.
* changed `BSON` imports in integration tests to be from Stitch modules rather than from `"bson"`
I've also verified that `BSON` is usable in the generated `stitch.js` for use in script tags.

STITCH-2341 Export BSON library with SDKs at top level

---

README.md
contrib/publish_docs.sh
packages/browser/sdk/README.md
packages/react-native/sdk/README.md
packages/server/sdk/README.md

This updates the destination to a stitch-sdks subdirectory on the
existing bucket so that docs.mongodb.com/stitch-sdks can find it.
(Not sure, this was specifically required by techops.)
Removes the /docs/ part which is arguably redundant now that it is
hosted on docs.mongodb.com.
Also updates the READMEs for the new docs URL. Please publish
the docs and check that the new URL works.

DOCSP-3936 Push docs to docs.mongodb.com

---

contrib/generate_docs.sh
contrib/publish_docs.sh
package.json
typedoc-theme/src/partials/analytics.hbs

This injects the Segment analytics snippet to all pages via
the custom TypeDoc theme.
Adds a script for building the docs so that analytics are only
added when publishing docs, and not for local docs builds.

DOCSP-3937 Add analytics snippet to all SDK pages

---

packages/browser/services/mongodb-remote/src/RemoteMongoCollection.ts
packages/core/sdk/src/auth/StitchCredential.ts
packages/react-native/core/src/core/Stitch.ts
packages/react-native/core/src/core/StitchAppClient.ts
packages/react-native/core/src/core/auth/StitchAuth.ts
packages/react-native/core/src/core/auth/StitchUser.ts
packages/react-native/services/mongodb-remote/src/RemoteMongoClient.ts
packages/react-native/services/mongodb-remote/src/RemoteMongoCollection.ts
packages/react-native/services/mongodb-remote/src/RemoteMongoCursor.ts
packages/react-native/services/mongodb-remote/src/RemoteMongoDatabase.ts
packages/react-native/services/mongodb-remote/src/RemoteMongoReadOperation.ts
packages/server/core/src/core/Stitch.ts
packages/server/core/src/core/StitchAppClient.ts
packages/server/core/src/core/auth/StitchAuth.ts
packages/server/core/src/core/auth/StitchUser.ts
packages/server/services/mongodb-remote/src/RemoteMongoClient.ts
packages/server/services/mongodb-remote/src/RemoteMongoCollection.ts
packages/server/services/mongodb-remote/src/RemoteMongoCursor.ts
packages/server/services/mongodb-remote/src/RemoteMongoDatabase.ts
packages/server/services/mongodb-remote/src/RemoteMongoReadOperation.ts

- Copies the changes made previously to browser docs into the other
SDK docs.
- Net new content is effectively zero
- Attention paid to scrubbing references to RedirectCredential and
also Stitch's persistence across sessions.
- Remove references to collection 'watch' in RN and Server SDKs.
Staged changes:
https://docs-mongodbcom-staging.corp.mongodb.com/stitch/bush/docsp-4282-copy-docs/sdk/js-server/index.html
https://docs-mongodbcom-staging.corp.mongodb.com/stitch/bush/docsp-4282-copy-docs/sdk/react-native/index.html

DOCSP-4282 Copy changes in browser to server, RN docs

---

contrib/generate_docs.sh
contrib/stage_docs.sh
typedoc-theme/build.sh
typedoc-theme/check_install.sh
typedoc-theme/gruntfile.js
typedoc-theme/package-lock.json
typedoc-theme/package.json
typedoc-theme/src/layouts/default.hbs
typedoc-theme/src/partials/rating-panel.hbs

On the site only (or, more precisely, when Typedoc theme is generated with analytics enabled).
- Pulls standalone feedback widget js/css from docs-tools github.
- Updates typedoc build script to check cached checksum.
Staged changes:
https://docs-mongodbcom-staging.corp.mongodb.com/stitch/bush/docsp-4263-feedback/sdk/js/index.html
https://docs-mongodbcom-staging.corp.mongodb.com/stitch/bush/docsp-4263-feedback/sdk/js-server/index.html
https://docs-mongodbcom-staging.corp.mongodb.com/stitch/bush/docsp-4263-feedback/sdk/react-native/index.html

DOSCP-4263 Add feedback widget to SDK docs

---

packages/browser/services/mongodb-remote/__tests__/RemoteMongoClientIntTests.ts
packages/browser/services/mongodb-remote/src/RemoteMongoCollection.ts
packages/browser/services/mongodb-remote/src/internal/RemoteMongoCollectionImpl.ts
packages/core/sdk/src/auth/internal/CoreStitchAuth.ts
packages/core/services/mongodb-remote/__tests__/CoreRemoteMongoCollectionUnitTests.ts
packages/core/services/mongodb-remote/src/internal/CoreRemoteMongoCollection.ts
packages/core/services/mongodb-remote/src/internal/CoreRemoteMongoCollectionImpl.ts
packages/react-native/core/package-lock.json
packages/react-native/coretest/package-lock.json
packages/react-native/services/aws-s3/package-lock.json
packages/react-native/services/aws-ses/package-lock.json
packages/react-native/services/aws/package-lock.json
packages/react-native/services/http/package-lock.json
packages/react-native/services/mongodb-remote/__tests__/RemoteMongoClientIntTests.ts
packages/react-native/services/mongodb-remote/package-lock.json
packages/react-native/services/mongodb-remote/src/RemoteMongoCollection.ts
packages/react-native/services/mongodb-remote/src/internal/RemoteMongoCollectionImpl.ts
packages/react-native/services/twilio/package-lock.json
packages/server/services/mongodb-remote/__tests__/RemoteMongoClientIntTests.ts
packages/server/services/mongodb-remote/src/RemoteMongoCollection.ts
packages/server/services/mongodb-remote/src/internal/RemoteMongoCollectionImpl.ts

Not sure if this is a big deal/wrong, but the findOne() method returns null as opposed to undefined when there are no matching documents. We can discuss if this is not the right behaviour.

Add findOne() functionality

---

packages/core/sdk/src/auth/internal/CoreStitchAuth.ts

If switchUserWithId throws one of its potential errors within the Promise.resolve, it goes unhandled and crashes the page.

 Wrap switchUserWithId in try catch

---

packages/browser/services/mongodb-remote/__tests__/RemoteMongoClientIntTests.ts
packages/core/sdk/src/auth/internal/CoreStitchAuth.ts
packages/react-native/core/package-lock.json
packages/react-native/coretest/package-lock.json
packages/react-native/services/aws-s3/package-lock.json
packages/react-native/services/aws-ses/package-lock.json
packages/react-native/services/aws/package-lock.json
packages/react-native/services/http/package-lock.json
packages/react-native/services/mongodb-remote/__tests__/RemoteMongoClientIntTests.ts
packages/react-native/services/mongodb-remote/package-lock.json
packages/react-native/services/twilio/package-lock.json
packages/server/services/mongodb-remote/__tests__/RemoteMongoClientIntTests.ts

Are we worried about this being a breaking change for people's code?

Stitch-2630: Requests without Auth should Reject Promise

---

contrib/README.md
contrib/update_browser_readme_version.sh

Please run contrib/update_browser_readme_version.sh when releasing/publishing
docs.

DOCSP-4862 Add script to update browser sdk README versions

---

contrib/docs-examples/checksum
typedoc-theme/src/partials/rating-panel.hbs

The intercom trial is over, so this removes the intercom bubble.
This also (inadvertently*) updates the feedback widget.
*-but we wanted to anyway! See https://jira.mongodb.org/browse/DOCSP-5312
Intercom bubble is seen here:
Staged:
https://docs-mongodbcom-staging.corp.mongodb.com/stitch/bush/docsp-5313-remove-intercom/sdk/js/index.html
https://docs-mongodbcom-staging.corp.mongodb.com/stitch/bush/docsp-5313-remove-intercom/sdk/js-server/index.html
https://docs-mongodbcom-staging.corp.mongodb.com/stitch/bush/docsp-5313-remove-intercom/sdk/react-native/index.html

DOCSP-5313 Remove intercom bubble from docs and update feedback widget

---

packages/browser/services/mongodb-remote/__tests__/RemoteMongoClientIntTests.ts
packages/browser/services/mongodb-remote/src/RemoteMongoCollection.ts
packages/browser/services/mongodb-remote/src/internal/RemoteMongoCollectionImpl.ts
packages/core/services/mongodb-remote/__tests__/CoreRemoteMongoCollectionUnitTests.ts
packages/core/services/mongodb-remote/src/CompactChangeEvent.ts
packages/core/services/mongodb-remote/src/index.ts
packages/core/services/mongodb-remote/src/internal/CoreRemoteMongoCollection.ts
packages/core/services/mongodb-remote/src/internal/CoreRemoteMongoCollectionImpl.ts
packages/core/services/mongodb-remote/src/internal/ResultDecoders.ts
packages/server/services/mongodb-remote/__tests__/RemoteMongoClientIntTests.ts
packages/server/services/mongodb-remote/src/RemoteMongoCollection.ts
packages/server/services/mongodb-remote/src/internal/RemoteMongoCollectionImpl.ts

This PR adds:
* `CompactChangeEvent` which is the type of event that compact streams return. 
* Unlike Java and Swift, this does not share a base type with ChangeEvent. The code duplication is minimal in JS compared to Java and Swift
* a `CompactChangeEventDecoder` to `ResultDecoders` in the remote MongoDB service.
* an `UpdateDescriptionDecoder` to `ResultDecoders` to avoid duplicating code between the two change event decoders.
* `watchCompact` to the remote mongo collections in the browser and server SDKs
* Integration tests for `watchCompact` (@dkaminsky and I'm testing one thing per test 😄  )
* Unit tests for both `watch` and `watchCompact` since there was previously no unit test for `watch`

STITCH-2717 add support for compact watch streams

---

packages/browser/services/mongodb-remote/src/RemoteMongoCollection.ts
packages/server/services/mongodb-remote/src/RemoteMongoCollection.ts

- Includes note that the match expression filters against the change event
and is similar to triggers.
Browser
https://docs-mongodbcom-staging.corp.mongodb.com/stitch/bush/docsp-5244-watch-js/sdk/js/index.html
Server
https://docs-mongodbcom-staging.corp.mongodb.com/stitch/bush/docsp-5244-watch-js/sdk/js-server/index.html
(N/A to React Native)

DOCSP-5244 Touch up wording of JS SDK watch docs

---

test/admin/graphql.test.js

The GraphQL endpoints will error if there's no mongo service with rules defined. We need to bootstrap the app for GQL before running these tests.

STITCH-4428: Create a service and rule before doing GQL tests

---

src/admin.js
src/client.js
src/constants.js
test/admin/admin_triggers.test.js
test/constants.js
test/fixtures/stitch_mongo_fixture.js
test/testutil.js

Jira Ticket: https://jira.mongodb.org/browse/STITCH-4437
This ticket adds support for the endpoints necessary for the admin triggers console.

STITCH-4437: Add support for private admin triggers endpoints

---

src/admin.js
test/admin/sync.test.js

Since we now have sync config/methods under sync instead of realm we need to change the sdk to support it
Also now that we have language support, we can add a sync schema gen success test for the sdk

STITCH-4698 - change realm sdk methods to sync and add schema gen success test

---

src/admin.js
test/admin/sync.test.js
test/testutil.js

This update adds query param support for:
- service delete
- rule create/update/delete
With this we can run those functions `allow_destructive_changes` when we want to ignore a destructive sync error.
As this update is not implementation specific, and since the idea of what is or is not destructive has not been finalized yet I opted not to add tests. Let me know if there's a better way to test or mock general param behavior!

REALMC-5056 -  support queryParams for service delete and rule create, update, delete

---

test/admin/sync.test.js

Since we no longer support removing a sync service with the destructive changes flag (at least for now), we should remove the added test so all tests pass
https://github.com/10gen/baas/pull/2578#discussion_r414478869

REALMC-5437 - remove sync destructive service delete test

---

test/admin/app.test.js
test/auth.test.js
test/client/aws_services.test.js
test/client/execute_function.test.js
test/client/twilio_service.test.js
test/userRegistrations.test.js

The app cache was not being invalidated because the test setup requests were coming in too quickly.

REALMC-9230: fix failing test in 'stitch-js-sdk-3.0'
